name: Build ROXVIA EV APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Android project
        run: |
          rm -rf project
          mkdir project
          unzip -q ROXVIACR.zip -d project

          echo "Project files:"
          find project -maxdepth 2 -type f

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Build Debug APK
        working-directory: project
        run: |
          gradle assembleDebug --stacktrace

      - name: Find APK
        run: |
          find project -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ROXVIA-EV-APK
          path: project/**/build/outputs/apk/debug/*.apk
          if-no-files-found: error
