name: Build ROXVIA EV APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Android project
        run: |
          mkdir project
          unzip -q ROXVIACR.zip -d project

          echo "Extracted files:"
          find project -maxdepth 3 -type f | head -100

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Build APK
        working-directory: project
        run: |
          gradle assembleRelease --stacktrace

      - name: Find APK
        run: |
          find project -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ROXVIA-EV-APK
          path: project/**/build/outputs/apk/release/*.apk
          if-no-files-found: error
