name: Build ROXVIA EV APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Android project
        run: |
          rm -rf project
          mkdir project
          unzip -q ROXVIACR.zip -d project

      - name: Fix KSP compatibility
        working-directory: project
        run: |
          sed -i 's/googleDevtoolsKsp = "2.3.5"/googleDevtoolsKsp = "2.2.10-2.0.2"/' gradle/libs.versions.toml

          echo "KSP version:"
          grep googleDevtoolsKsp gradle/libs.versions.toml

      - name: Allow Kotlin source sets
        working-directory: project
        run: |
          echo "android.disallowKotlinSourceSets=false" >> gradle.properties

      - name: Create Android debug keystore
        working-directory: project
        run: |
          rm -f debug.keystore
          keytool -genkeypair \
            -v \
            -keystore debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

          ls -lh debug.keystore

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Build Debug APK
        working-directory: project
        run: |
          gradle assembleDebug --stacktrace

      - name: Find APK
        run: |
          find project -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ROXVIA-EV-APK
          path: project/**/build/outputs/apk/debug/*.apk
          if-no-files-found: error
